/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.39
 * Generated at: 2017-02-20 03:24:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class CartPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/jstl-jstl-1.2.jar", Long.valueOf(1487237213619L));
    _jspx_dependants.put("jar:file:/D:/New%20Workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/OrganoCart/WEB-INF/lib/jstl-jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("jar:file:/D:/New%20Workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/OrganoCart/WEB-INF/lib/jstl-jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153365282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Organocart - Cart Page</title>\r\n");
      out.write("<script src=\"resources/js/angular.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tvar cartproductlist = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${itemsincart}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\r\n");
      out.write("\tangular.module('organocartpackage', []).controller('CartController',\r\n");
      out.write("\t\t\tfunction($scope) {\r\n");
      out.write("\t\t\t\t$scope.citems = cartproductlist;\r\n");
      out.write("\t\t\t});\r\n");
      out.write("</script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".table>thead {\r\n");
      out.write("\tbackground-color: #8BC34A;\r\n");
      out.write("\tcolor: #ffffff;\r\n");
      out.write("\tfont-style: italic;\r\n");
      out.write("\tpadding: 10px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tvertical-align: middle;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".table>tfoot {\r\n");
      out.write("\tbackground-color: #8BC34A;\r\n");
      out.write("\tcolor: #ffffff;\r\n");
      out.write("\tfont-style: italic;\r\n");
      out.write("\tpadding: 10px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".table-striped>tbody>tr:nth-of-type(even) {\r\n");
      out.write("\tbackground-color: #dcedc8;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#removebtn {\r\n");
      out.write("\tcolor: #ffffff;\r\n");
      out.write("\tbackground-color: #e57373;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#removebtn:hover {\r\n");
      out.write("\tcolor: #ffffff;\r\n");
      out.write("\tbackground-color: #e53935;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#prodimage {\r\n");
      out.write("\twidth: 125px;\r\n");
      out.write("\theight: 150px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("tr {\r\n");
      out.write("\tmargin: 10px;\r\n");
      out.write("\tbackground-color: #9ccc65;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("th {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tmargin: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("td {\r\n");
      out.write("\tvertical-align: middle !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#jumbotrondiv {\r\n");
      out.write("\tbackground-color: #dcedc8;\r\n");
      out.write("\twidth: 80%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#quantity {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("#quantity:FOCUS\r\n");
      out.write("{\r\n");
      out.write("\toutline: none;\r\n");
      out.write("\tbox-shadow:none;\r\n");
      out.write("}\r\n");
      out.write("#minusbutton, #plusbutton {\r\n");
      out.write("\tpadding: 9px;\r\n");
      out.write("\tcolor: #ffffff;\r\n");
      out.write("\tbackground: linear-gradient(to bottom, #9ccc65 50%, #8bc34a 50%);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#checkoutbutton,#continuebutton {\r\n");
      out.write("\tcolor: #ffffff;\r\n");
      out.write("\tbackground: linear-gradient(to bottom, #9ccc65 50%, #8bc34a 50%);\r\n");
      out.write("}\r\n");
      out.write("#checkoutbutton:HOVER,#continuebutton:HOVER {\r\n");
      out.write("\tbackground: linear-gradient(to bottom, #aed581 50%, #9ccc65 50%);\r\n");
      out.write("\tcolor: #ffffff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("<body ng-app=\"organocartpackage\" ng-controller=\"CartController\">\r\n");
      out.write("\t<div class=\"container\" style=\"min-height: 400px;\">\r\n");
      out.write("\t\t<h3 style=\"text-align: center; color: #689f38\"\r\n");
      out.write("\t\t\tstyle=\" border-radius: 5px\">Cart Page</h3>\r\n");
      out.write("\r\n");
      out.write("\t\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/CartPage.jsp(106,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cartempty}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t<div class=\"jumbotron container h4 animated fadeInDown delay-05s\" id=\"jumbotrondiv\" align=\"center\">\r\n");
          out.write("\t\t\t\tThere are No items in the cart<br>\r\n");
          out.write("\t\t\t\t<br>\r\n");
          out.write("\t\t\t\t<br> \r\n");
          out.write("\t\t\t\t<a href=\"buyproductpage\" type=\"button\" id=\"continuebutton\"\r\n");
          out.write("\t\t\t\t\tclass=\"btn\"><span class=\"glyphicon glyphicon-shopping-cart\"></span>\r\n");
          out.write("\t\t\t\t\tBuy Products</a>\r\n");
          out.write("\t\t\t</div>\r\n");
          out.write("\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/CartPage.jsp(116,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!cartempty}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t<table class=\"table table-striped table-responsive animated fadeInDown delay-05s\">\r\n");
          out.write("\t\t\t\t<thead>\r\n");
          out.write("\t\t\t\t\t<tr scope=\"row\">\r\n");
          out.write("\t\t\t\t\t\t<th style=\"width: 10%\">Product</th>\r\n");
          out.write("\t\t\t\t\t\t<th style=\"width: 10%\">Product Name</th>\r\n");
          out.write("\t\t\t\t\t\t<th style=\"width: 15%\">Quantity</th>\r\n");
          out.write("\t\t\t\t\t\t<th style=\"width: 7%\">Total Price</th>\r\n");
          out.write("\t\t\t\t\t\t<th style=\"width: 7%\">Payable Amount</th>\r\n");
          out.write("\t\t\t\t\t\t<th style=\"width: 10%\"></th>\r\n");
          out.write("\t\t\t\t\t</tr>\r\n");
          out.write("\t\t\t\t</thead>\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t<tbody ng-repeat=\"items in citems\">\r\n");
          out.write("\t\t\t\t\t<tr scope=\"row\" style=\"margin: 10px\">\r\n");
          out.write("\t\t\t\t\t\t<td><img id=\"prodimage\" src=\"resources/Pimage/{{items.pid}}.jpg\"\r\n");
          out.write("\t\t\t\t\t\t\tclass=\"img-rounded\"></td>\r\n");
          out.write("\t\t\t\t\t\t<td class=\"h4\">{{items.pname}}</td>\r\n");
          out.write("\t\t\t\t\t\t<td><div class=\"input-group\">\r\n");
          out.write("\t\t\t\t\t\t\t\t<span class=\"input-group-btn\"> <a\r\n");
          out.write("\t\t\t\t\t\t\t\t\thref=\"editquantity?getproductid={{items.pid}}&value=decrease\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\tid=\"minusbutton\" type=\"button\" class=\"btn\"> <span\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-minus\"></span>\r\n");
          out.write("\t\t\t\t\t\t\t\t</a>\r\n");
          out.write("\t\t\t\t\t\t\t\t</span> <input type=\"text\" id=\"quantity\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\tclass=\"form-control input-number\" value=\"{{items.qty}}\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\treadonly=\"readonly\" onfocus=\"this.blur()\"> <span class=\"input-group-btn\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<a\r\n");
          out.write("\t\t\t\t\t\t\t\t\thref=\"editquantity?getproductid={{items.pid}}&value=increase\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\tid=\"plusbutton\" type=\"button\" class=\"btn\"> <span\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-plus\"></span>\r\n");
          out.write("\t\t\t\t\t\t\t\t</a>\r\n");
          out.write("\t\t\t\t\t\t\t\t</span>\r\n");
          out.write("\t\t\t\t\t\t\t</div></td>\r\n");
          out.write("\t\t\t\t\t\t<td>Rs.{{items.price}}</td>\r\n");
          out.write("\t\t\t\t\t\t<td>Rs.{{items.total}}</td>\r\n");
          out.write("\t\t\t\t\t\t<td><a href=\"removeproductitem?pid={{items.pid}}\"\r\n");
          out.write("\t\t\t\t\t\t\tid=\"removebtn\" class=\"btn btn-outline-danger\"> <span\r\n");
          out.write("\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-remove\"></span> Remove\r\n");
          out.write("\t\t\t\t\t\t</a></td>\r\n");
          out.write("\t\t\t\t\t</tr>\r\n");
          out.write("\t\t\t\t</tbody>\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t<tfoot>\r\n");
          out.write("\t\t\t\t\t<td></td>\r\n");
          out.write("\t\t\t\t\t<td></td>\r\n");
          out.write("\t\t\t\t\t<td></td>\r\n");
          out.write("\t\t\t\t\t<td>\r\n");
          out.write("\t\t\t\t\t\t<div class=\"pull-left\">\r\n");
          out.write("\t\t\t\t\t\t\t<h4>\r\n");
          out.write("\t\t\t\t\t\t\t\t<b>Grand Total</b>\r\n");
          out.write("\t\t\t\t\t\t\t</h4>\r\n");
          out.write("\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t</td>\r\n");
          out.write("\t\t\t\t\t<td><h4 class=\"pull-left\">\r\n");
          out.write("\t\t\t\t\t\t\t<b>Rs.");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.grandtotal}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</b>\r\n");
          out.write("\t\t\t\t\t\t</h4>\r\n");
          out.write("\t\t\t\t\t</td>\r\n");
          out.write("\t\t\t\t\t<td></td>\r\n");
          out.write("\t\t\t\t</tfoot>\r\n");
          out.write("\t\t\t</table>\r\n");
          out.write("\t\t\t<div class=\"pull-right\" style=\"display: inline-block\">\r\n");
          out.write("\t\t\t<a href=\"buyproductpage\" type=\"button\" id=\"continuebutton\"\r\n");
          out.write("\t\t\t\t\tclass=\"btn\"><span\r\n");
          out.write("\t\t\t\t\tclass=\"glyphicon glyphicon-shopping-cart\"></span> Continue shopping</a>\r\n");
          out.write("\t\t\t<a href=\"billingaddresspage\" class=\"btn\" id=\"checkoutbutton\"><span\r\n");
          out.write("\t\t\t\t\tclass=\"glyphicon glyphicon-tasks\"></span> Proceed To Order </a>\t\r\n");
          out.write("\t\t\t</div>\r\n");
          out.write("\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    }
    return false;
  }
}
