/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.39
 * Generated at: 2017-02-20 06:59:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/bootstrap-theme.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/bootstrap-theme.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/animate.css\">\r\n");
      out.write("\r\n");
      out.write("<script src=\"resources/js/bootstrap.js\"></script>\r\n");
      out.write("<script src=\"resources/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"resources/js/angular.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Home-OrganoCart</title>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".carousel-inner>.item>img, .carousel-inner>.item>a>img {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 440px;\r\n");
      out.write("\tmax-height: 400px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".panel {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tbackground-color: #ffffff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".panel:hover {\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\tbackground-color: #dcedc8;\r\n");
      out.write("\t-webkit-transition: background-color ease-in 0.4s;\r\n");
      out.write("\ttransition: background-color ease-in 0.4s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#addtocartbutton, #viewproductsbutton {\r\n");
      out.write("\tbackground-color: #9CCC65;\r\n");
      out.write("\tcolor: #ffffff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#addtocartbutton:hover, #viewproductsbutton:hover {\r\n");
      out.write("\tbackground-color: #aed581;\r\n");
      out.write("\tcolor: #ffffff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#productimage:hover {\r\n");
      out.write("\ttransition: all 0.5s ease;\r\n");
      out.write("\ttransform: scale(1.07);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#pricediv {\r\n");
      out.write("\ttext-align: right;\r\n");
      out.write("\tfont-size: 20px;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\tfont-family: sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#producta {\r\n");
      out.write("\tcolor: #000000;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#welldiv {\r\n");
      out.write("\tbackground-color: #ffffff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#loginproductsbutton {\r\n");
      out.write("\tcolor: #ffffff;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tmargin-right: 110px;\r\n");
      out.write("\tbackground: linear-gradient(to bottom, #aed581 50%, #9ccc65 50%);\r\n");
      out.write("}\r\n");
      out.write("#loginproductsbutton:HOVER {\r\n");
      out.write("\tbackground: linear-gradient(to bottom, #9ccc65 50%, #8bc34a 50%);\t\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("\tvar productlist = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productlist}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\r\n");
      out.write("\tangular.module('organocartpackage', []).controller('ProductController',\r\n");
      out.write("\t\t\tfunction($scope) {\r\n");
      out.write("\t\t\t\t$scope.productangularobject = productlist;\r\n");
      out.write("\t\t\t});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("<body style=\"background-color: #ffffff\">\r\n");
      out.write("\t<div class=\"column\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"myCarousel\" class=\"carousel slide animated fadeIn delay-08s\" data-ride=\"carousel\">\r\n");
      out.write("\t\t\t<!-- Indicators -->\r\n");
      out.write("\t\t\t<ol class=\"carousel-indicators\">\r\n");
      out.write("\t\t\t\t<li data-target=\"#myCarousel\" data-slide-to=\"0\" class=\"active\"></li>\r\n");
      out.write("\t\t\t\t<li data-target=\"#myCarousel\" data-slide-to=\"1\"></li>\r\n");
      out.write("\t\t\t\t<li data-target=\"#myCarousel\" data-slide-to=\"2\"></li>\r\n");
      out.write("\t\t\t\t<li data-target=\"#myCarousel\" data-slide-to=\"3\"></li>\r\n");
      out.write("\t\t\t</ol>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Wrapper for slides -->\r\n");
      out.write("\t\t\t<div class=\"carousel-inner\" role=\"listbox\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"item active\">\r\n");
      out.write("\t\t\t\t\t<img src=\"resources/img/organicproducts4.jpg\" alt=\"fourthimage\"\r\n");
      out.write("\t\t\t\t\t\twidth=\"460px\" height=\"440px\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t<img src=\"resources/img/organicproducts1.jpg\" alt=\"firstimage\"\r\n");
      out.write("\t\t\t\t\t\twidth=\"460px\" height=\"440px\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t<img src=\"resources/img/organicproducts2.jpg\" alt=\"secondimage\"\r\n");
      out.write("\t\t\t\t\t\twidth=\"460px\" height=\"440px\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t<img src=\"resources/img/organicproducts3.jpg\" alt=\"thirdimage\"\r\n");
      out.write("\t\t\t\t\t\twidth=\"460px\" height=\"440px\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Left and right controls -->\r\n");
      out.write("\t\t\t<a class=\"left carousel-control\" href=\"#myCarousel\" role=\"button\"\r\n");
      out.write("\t\t\t\tdata-slide=\"prev\"> <span\r\n");
      out.write("\t\t\t\tclass=\"glyphicon glyphicon-chevron-left\" aria-hidden=\"true\"></span>\r\n");
      out.write("\t\t\t\t<span class=\"sr-only\">Previous</span>\r\n");
      out.write("\t\t\t</a> <a class=\"right carousel-control\" href=\"#myCarousel\" role=\"button\"\r\n");
      out.write("\t\t\t\tdata-slide=\"next\"> <span\r\n");
      out.write("\t\t\t\tclass=\"glyphicon glyphicon-chevron-right\" aria-hidden=\"true\"></span>\r\n");
      out.write("\t\t\t\t<span class=\"sr-only\">Next</span>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"welldiv\" ng-app=\"organocartpackage\"\r\n");
      out.write("\t\t\tng-controller=\"ProductController\">\r\n");
      out.write("\t\t\t<h3 style=\"text-align: center;\">Products</h3>\r\n");
      out.write("\t\t\t<div class=\"panel scroll animated fadeInUp delay-05s\" style=\"margin-left: 50px;\"\r\n");
      out.write("\t\t\t\tng-repeat=\"p in productangularobject | limitTo: 4\">\r\n");
      out.write("\t\t\t\t<a href=\"viewproduct?getId={{p.ProductId}}\" id=\"producta\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<img id=\"productimage\" class=\"img-rounded img-fluid\"\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"resources/Pimage/{{p.ProductId}}.jpg\" height=\"200px\"\r\n");
      out.write("\t\t\t\t\t\t\twidth=\"200px\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"lead\" style=\"margin-top: 5px\">{{p.ProductName}}</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"\">{{p.ProductDescription}}</div>\r\n");
      out.write("\t\t\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"pricediv\">\r\n");
      out.write("\t\t\t\t\t\t\t<strong style=\"margin-top: 10px\">Rs.{{p.ProductPrice}}</strong>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<a href=\"buyproductpage\" class=\"btn pull-right\" id=\"loginproductsbutton\"><span\r\n");
      out.write("\t\t\t\tclass=\"glyphicon glyphicon-hand-right\"></span>&nbsp; View More Products</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
