/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.39
 * Generated at: 2017-02-20 07:09:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Invoice_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-jstl-1.2.jar", Long.valueOf(1487237213619L));
    _jspx_dependants.put("jar:file:/D:/New%20Workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/OrganoCart/WEB-INF/lib/jstl-jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Invoice - Organocart</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("#emailinvoicebtn, #continuebutton {\r\n");
      out.write("\tbackground-color: #9ccc65;\r\n");
      out.write("\tcolor: #ffffff;\r\n");
      out.write("\tbackground: linear-gradient(to bottom, #aed581 50%, #9ccc65 50%);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#emailinvoicebtn:HOVER, #continuebutton:HOVER {\r\n");
      out.write("\tcolor: #ffffff;\r\n");
      out.write("\tbackground-color: #aed581;\r\n");
      out.write("\tbackground: linear-gradient(to bottom, #9ccc65 50%, #8bc34a 50%);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#emailbox:FOCUS {\r\n");
      out.write("\tborder: 2px solid #9ccc65;\r\n");
      out.write("\tborder-radius: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#welldiv {\r\n");
      out.write("\tbackground-color: #dcedc8;\r\n");
      out.write("\tpadding: 20px;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#prodimage {\r\n");
      out.write("\twidth: 100px;\r\n");
      out.write("\theight: 125px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#jumbotrondiv {\r\n");
      out.write("\tbackground-color: #dcedc8;\r\n");
      out.write("\twidth: 80%;\r\n");
      out.write("\tborder-radius:10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-control:FOCUS {\r\n");
      out.write("\tborder: 2px solid #9ccc65;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script src=\"resources/js/angular.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tvar cartproductlist = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${itemsincart}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\r\n");
      out.write("\tvar addressjson = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${addressobject}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\r\n");
      out.write("\tangular.module('organocartpackage', []).controller('InvoiceController',\r\n");
      out.write("\t\t\tfunction($scope) {\r\n");
      out.write("\t\t\t\t$scope.citems = cartproductlist;\r\n");
      out.write("\t\t\t\t$scope.address = addressjson;\r\n");
      out.write("\t\t\t});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("<body style=\"margin-top: 10px\" ng-app=\"organocartpackage\" ng-controller=\"InvoiceController\">\r\n");
      out.write("\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      out.write('	');
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/Invoice.jsp(62,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bill}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t<div class=\"row\" style=\"min-height: 400px;\">\r\n");
          out.write("\t\t\t<div id=\"welldiv\" style=\"border-radius: 5px;\"\r\n");
          out.write("\t\t\t\tclass=\"col-xs-10 col-sm-10 col-md-6 col-xs-offset-1 col-sm-offset-1 col-md-offset-3\">\r\n");
          out.write("\t\t\t\t<div class=\"row\">\r\n");
          out.write("\t\t\t\t\t<div class=\"col-xs-4 col-sm-4 col-md-4\">\r\n");
          out.write("\t\t\t\t\t\t<address>\r\n");
          out.write("\t\t\t\t\t\t\t<strong>{{address.UserName}}</strong> <br>\r\n");
          out.write("\t\t\t\t\t\t\t{{address.AddressLine1}}, <br> {{address.AddressLine2}},<br>\r\n");
          out.write("\t\t\t\t\t\t\t{{address.City}} - {{address.Pincode}} <br> Phone :\r\n");
          out.write("\t\t\t\t\t\t\t{{address.PhoneNumber}}\r\n");
          out.write("\t\t\t\t\t\t</address>\r\n");
          out.write("\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t<div class=\"col-xs-4 col-sm-4 col-md-4 text-right\">\r\n");
          out.write("\t\t\t\t\t\t<span style=\"display: block\"> <img class=\"img-rounded\"\r\n");
          out.write("\t\t\t\t\t\t\tsrc=\"resources/img/organocartfont.PNG\">\r\n");
          out.write("\t\t\t\t\t\t</span>\r\n");
          out.write("\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t<div class=\"col-xs-4 col-sm-4 col-md-4 text-right\">\r\n");
          out.write("\t\t\t\t\t\t<p>\r\n");
          out.write("\t\t\t\t\t\t\t<em>Date:");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.Date}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</em><br> <em>Order ID:\r\n");
          out.write("\t\t\t\t\t\t\t\t34522677W</em><br> <em>Invoice Id: 34522677W</em>\r\n");
          out.write("\t\t\t\t\t\t</p>\r\n");
          out.write("\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t<div class=\"row\">\r\n");
          out.write("\t\t\t\t\t<div class=\"text-center\">\r\n");
          out.write("\t\t\t\t\t\t<h1 style=\"color: #9ccc65\">\r\n");
          out.write("\t\t\t\t\t\t\t<em>Invoice</em>\r\n");
          out.write("\t\t\t\t\t\t</h1>\r\n");
          out.write("\t\t\t\t\t</div>\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t\t<table class=\"table table-striped\">\r\n");
          out.write("\t\t\t\t\t\t<thead>\r\n");
          out.write("\t\t\t\t\t\t\t<tr>\r\n");
          out.write("\t\t\t\t\t\t\t\t<th>Product</th>\r\n");
          out.write("\t\t\t\t\t\t\t\t<th></th>\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t<th>Quantity</th>\r\n");
          out.write("\t\t\t\t\t\t\t\t<th class=\"text-center\">Price</th>\r\n");
          out.write("\t\t\t\t\t\t\t\t<th class=\"text-center\">Total</th>\r\n");
          out.write("\t\t\t\t\t\t\t</tr>\r\n");
          out.write("\t\t\t\t\t\t</thead>\r\n");
          out.write("\t\t\t\t\t\t<tbody>\r\n");
          out.write("\t\t\t\t\t\t\t<tr ng-repeat=\"c in citems\">\r\n");
          out.write("\t\t\t\t\t\t\t\t<td><img id=\"prodimage\" alt=\"product image\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\tsrc=\"resources/Pimage/{{c.pid}}.jpg\" class=\"img-rounded\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<h4>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<em>{{c.pname}}</em>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t</h4></td>\r\n");
          out.write("\t\t\t\t\t\t\t\t<td></td>\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t<td class=\"col-md-1\" style=\"text-align: center\">{{c.qty}}</td>\r\n");
          out.write("\t\t\t\t\t\t\t\t<td class=\"col-md-1 text-center\">Rs.{{c.price}}</td>\r\n");
          out.write("\t\t\t\t\t\t\t\t<td class=\"col-md-1 text-center\">Rs.{{c.total}}</td>\r\n");
          out.write("\t\t\t\t\t\t\t</tr>\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t<tr>\r\n");
          out.write("\t\t\t\t\t\t\t\t<td></td>\r\n");
          out.write("\t\t\t\t\t\t\t\t<td></td>\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t<td class=\"text-right\"><h4>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<strong>Grand</strong>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t</h4></td>\r\n");
          out.write("\t\t\t\t\t\t\t\t<td class=\"text-right\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<h4>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<strong>Total:</strong>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t</h4>\r\n");
          out.write("\t\t\t\t\t\t\t\t</td>\r\n");
          out.write("\t\t\t\t\t\t\t\t<td class=\"text-center text-danger\"><h4>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<strong>Rs.");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.grandtotal}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</strong>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t</h4></td>\r\n");
          out.write("\t\t\t\t\t\t\t</tr>\r\n");
          out.write("\t\t\t\t\t\t</tbody>\r\n");
          out.write("\t\t\t\t\t</table>\r\n");
          out.write("\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t<form action=\"emailingreceipt\">\r\n");
          out.write("\t\t\t\t\t<div class=\"col-sm-8\">\r\n");
          out.write("\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"emailbox\"\r\n");
          out.write("\t\t\t\t\t\t\tplaceholder=\"send receipt to this email id\" name=\"email\"\r\n");
          out.write("\t\t\t\t\t\t\trequired=\"true\">\r\n");
          out.write("\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t<div class=\"col-sm-4\">\r\n");
          out.write("\t\t\t\t\t\t<button id=\"emailinvoicebtn\" type=\"submit\" class=\"btn\">\r\n");
          out.write("\t\t\t\t\t\t\tEmail Invoice<span class=\"glyphicon glyphicon-chevron-right\"></span>\r\n");
          out.write("\t\t\t\t\t\t</button>\r\n");
          out.write("\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t</form>\r\n");
          out.write("\t\t\t</div>\r\n");
          out.write("\t\t</div>\r\n");
          out.write("\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/Invoice.jsp(153,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!bill}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\r\n");
          out.write("\t\t<div class=\"jumbotron container h4\" id=\"jumbotrondiv\" align=\"center\"\r\n");
          out.write("\t\t\tstyle=\"min-height: 600px;\">\r\n");
          out.write("\t\t\t");
          if (_jspx_meth_c_005fif_005f2(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t");
          if (_jspx_meth_c_005fif_005f3(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t</div>\r\n");
          out.write("\r\n");
          out.write("\r\n");
          out.write("\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /WEB-INF/views/Invoice.jsp(157,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${success}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\tThanks for shopping with us.<br>\r\n");
          out.write("\t\t\t\t<br> The Invoice has been mailed to you since we are trying to be as eco-friendly as possible.<br>\r\n");
          out.write("\t\t\t\t<br>\r\n");
          out.write("\t\t\tHappy Shopping with Organocart<br>\r\n");
          out.write("\t\t\t\t<br>\r\n");
          out.write("\t\t\t\t<br>\r\n");
          out.write("\t\t\t\t<div style=\"display: inline-block\">\r\n");
          out.write("\t\t\t\t\t<a target=\"_newtab\" href=\"https://www.google.com/gmail/\"\r\n");
          out.write("\t\t\t\t\t\ttype=\"button\" id=\"continuebutton\" class=\"btn\"><span\r\n");
          out.write("\t\t\t\t\t\tclass=\"glyphicon glyphicon-envelope\"></span> Check Mail </a> <a\r\n");
          out.write("\t\t\t\t\t\thref=\"buyproductpage\" type=\"button\" id=\"continuebutton\"\r\n");
          out.write("\t\t\t\t\t\tclass=\"btn\"><span class=\"glyphicon glyphicon-shopping-cart\"></span>\r\n");
          out.write("\t\t\t\t\t\tBuy More Products</a>\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t\t<h3 style=\"color: #689f38\">\r\n");
          out.write("\t\t\t\t\t\tLove Nature <span class=\"glyphicon glyphicon-tree-deciduous\"></span>\r\n");
          out.write("\t\t\t\t\t\t<br><br>&emsp;&emsp;&emsp;Save Earth&nbsp;<i\r\n");
          out.write("\t\t\t\t\t\t\tclass=\"fa fa-globe\" aria-hidden=\"true\"></i>\r\n");
          out.write("\t\t\t\t\t</h3>\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t</div>\r\n");
          out.write("\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /WEB-INF/views/Invoice.jsp(180,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!success}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("<h3>Sorry For the inconvenience.</h3> <br>\r\n");
          out.write("\t\t\t\tEmail sending failed due to server error...Please try again later !!! Continue shopping until then<br>\r\n");
          out.write("\t\t\t\t<br>\r\n");
          out.write("\t\t\t\t<br>\r\n");
          out.write("\t\t\t\t<a href=\"buyproductpage\" type=\"button\" id=\"continuebutton\"\r\n");
          out.write("\t\t\t\t\tclass=\"btn\"><span class=\"glyphicon glyphicon-shopping-cart\"></span>\r\n");
          out.write("\t\t\t\t\tContinue Shopping</a>\r\n");
          out.write("\r\n");
          out.write("\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
    }
    return false;
  }
}
