/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.39
 * Generated at: 2017-02-20 06:16:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Login-Organocart</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".wrapper {\r\n");
      out.write("\tmargin-top: 20px;\r\n");
      out.write("\tmargin-bottom: 20px;\r\n");
      out.write("\tborder-radius: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-signin {\r\n");
      out.write("\tmax-width: 420px;\r\n");
      out.write("\tpadding: 30px 38px 66px;\r\n");
      out.write("\tmargin: 0 auto;\r\n");
      out.write("\tbackground-color: #eee;\r\n");
      out.write("\tborder: 3px dotted rgba(0, 0, 0, 0.1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-signin-heading {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tmargin-bottom: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-control {\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\tfont-size: 16px;\r\n");
      out.write("\theight: auto;\r\n");
      out.write("\tpadding: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=\"text\"] {\r\n");
      out.write("\tmargin-bottom: 0px;\r\n");
      out.write("\tborder-bottom-left-radius: 0;\r\n");
      out.write("\tborder-bottom-right-radius: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=\"password\"] {\r\n");
      out.write("\tmargin-bottom: 20px;\r\n");
      out.write("\tborder-top-left-radius: 0;\r\n");
      out.write("\tborder-top-right-radius: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#loginbutton {\r\n");
      out.write("\tbackground: linear-gradient(to bottom, #aed581 50%, #9ccc65 50%);\r\n");
      out.write("\tcolor: #ffffff;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tmargin-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#loginbutton:HOVER {\r\n");
      out.write("\tbackground: linear-gradient(to bottom, #9ccc65 50%, #8bc34a 50%);\t\r\n");
      out.write("\tcolor: #ffffff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#useridcontrol:FOCUS, #passwordcontrol:FOCUS {\r\n");
      out.write("\tborder: 2.5px solid #9ccc65;\r\n");
      out.write("}\r\n");
      out.write("#smileyimage\r\n");
      out.write("{\r\n");
      out.write("\theight:100px;\r\n");
      out.write("\twidth:100px;\r\n");
      out.write("\tmargin-top: 10px;\r\n");
      out.write("}\r\n");
      out.write(".colorgraph {\r\n");
      out.write("\theight: 7px;\r\n");
      out.write("\tborder-top: 0;\r\n");
      out.write("\tbackground: #c4e17f;\r\n");
      out.write("\tborder-radius: 5px;\r\n");
      out.write("\tbackground-image: -webkit-linear-gradient(left, #c4e17f, #c4e17f 12.5%, #f7fdca 12.5%,\r\n");
      out.write("\t\t#f7fdca 25%, #fecf71 25%, #fecf71 37.5%, #f0776c 37.5%, #f0776c 50%,\r\n");
      out.write("\t\t#db9dbe 50%, #db9dbe 62.5%, #c49cde 62.5%, #c49cde 75%, #669ae1 75%,\r\n");
      out.write("\t\t#669ae1 87.5%, #62c2e4 87.5%, #62c2e4);\r\n");
      out.write("\tbackground-image: -moz-linear-gradient(left, #c4e17f, #c4e17f 12.5%, #f7fdca 12.5%,\r\n");
      out.write("\t\t#f7fdca 25%, #fecf71 25%, #fecf71 37.5%, #f0776c 37.5%, #f0776c 50%,\r\n");
      out.write("\t\t#db9dbe 50%, #db9dbe 62.5%, #c49cde 62.5%, #c49cde 75%, #669ae1 75%,\r\n");
      out.write("\t\t#669ae1 87.5%, #62c2e4 87.5%, #62c2e4);\r\n");
      out.write("\tbackground-image: -o-linear-gradient(left, #c4e17f, #c4e17f 12.5%, #f7fdca 12.5%, #f7fdca\r\n");
      out.write("\t\t25%, #fecf71 25%, #fecf71 37.5%, #f0776c 37.5%, #f0776c 50%, #db9dbe\r\n");
      out.write("\t\t50%, #db9dbe 62.5%, #c49cde 62.5%, #c49cde 75%, #669ae1 75%, #669ae1\r\n");
      out.write("\t\t87.5%, #62c2e4 87.5%, #62c2e4);\r\n");
      out.write("\tbackground-image: linear-gradient(to right, #c4e17f, #c4e17f 12.5%, #f7fdca 12.5%, #f7fdca\r\n");
      out.write("\t\t25%, #fecf71 25%, #fecf71 37.5%, #f0776c 37.5%, #f0776c 50%, #db9dbe\r\n");
      out.write("\t\t50%, #db9dbe 62.5%, #c49cde 62.5%, #c49cde 75%, #669ae1 75%, #669ae1\r\n");
      out.write("\t\t87.5%, #62c2e4 87.5%, #62c2e4);\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("<body style=\"background-color: #dcedc8\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"wrapper animated fadeInUp delay-05s\">\r\n");
      out.write("\t\t\t<form action=\"perform_login\" method=\"post\" class=\"form-signin\">\r\n");
      out.write("\t\t\t\t<h3 class=\"form-signin-heading\" style=\"color: #9ccc65\">Hooray !! Welcome Back !!<img id=\"smileyimage\" alt=\"smiley\" src=\"resources/img/happiness.png\"></h3>\r\n");
      out.write("\t\t\t\t<hr class=\"colorgraph\">\r\n");
      out.write("\t\t\t\t<br> <input type=\"text\" class=\"form-control\" id=\"useridcontrol\"\r\n");
      out.write("\t\t\t\t\tplaceholder=\"Email Id\" id=\"usename\" name=\"usename\" required=\"true\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"password\" class=\"form-control\" id=\"passwordcontrol\"\r\n");
      out.write("\t\t\t\t\tplaceholder=\"Password\" id=\"userpassword\" name=\"userpassword\" required=\"true\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<button class=\"btn btn-lg\" name=\"Submit\" id=\"loginbutton\"\r\n");
      out.write("\t\t\t\t\tvalue=\"Login\" type=\"Submit\">Login</button>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<a href=\"Signup\" class=\"btn\" id=\"loginbutton\">New Users Sign Up Here </a>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
